baseurl = "https://sharonxu.com"
title = "DevOps with love"
theme = "hugo-coder-forked"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "kksudo"
enableGitInfo = true
enableRobotsTXT = true

# Hugo settings
[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.5

[params]
author = "Sharon Xu"
info = ["Data Scientist, Problem-Solver, Interdisciplinarian"]
description = "Sharon Xu's personal site"
keywords = "blog,businesscard,personal,devops,kksudo,kirill,kazakov"
avatarurl = "images/avatar.png"
faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon.png"

since = 2010
enableTwemoji = true
colorScheme = "auto"
hidecolorschemetoggle = false
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/sharonxu.com/tree/"
powered_by = true
# Series see also post count
maxSeeAlsoItems = 5

[taxonomies]
#tag = "tags"
#author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/kksudo/"
target = "_blank"
[[params.social]]
name = "Gitlab"
icon = "fa fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/kksudo"
target = "_blank"
[[params.social]]
name = "Instagram"
icon = "fa fa-instagram fa-2x"
weight = 3
url = "https://www.instagram.com/kk_sudo/"
target = "_blank"
[[params.social]]
name = "Linkedin"
icon = "fa fa-linkedin fa-2x"
weight = 5
url = "https://www.linkedin.com/in/kazakovk/"
target = "_blank"
[[params.social]]
name = "hello@sharonxu.com"
icon = "fa fa-envelope fa-2x"
weight = 6
url = "mailto:hello@sharonxu.com"
target = "_blank"

# Menu links
[[languages.en.menu.main]]
name = "Home"
weight = 1
url  = "/"
[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"


